config/routes.rb
Rails.application.routes.draw do
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 3}, confirmation: true,
            if: Proc.new { |u| u.new_record? or !u.password.blank? }

  def is_admin?()
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :check_app_auth
  before_action :load_current_user

  private
  def not_authenticated
    redirect_to login_path, alert: "Сначала войдите в систему!"
  end

  def load_current_user
    @current_user = current_user
  end

  def check_app_auth
    render 'access_denied' unless @current_user.try(:is_admin?)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_action :check_app_auth
  
  def new
    
  end
  
  def create
    @user = User.find_by_email(params[:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
    redirect_to(root_path, :notice => 'Инструкции по смене пароля отправлены на Вашу электронную почту.')
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(params[:id])

    if @user.blank?
      not_authenticated
      return
    end

    # the next line makes the password confirmation validation work
    @user.password_confirmation = params[:user][:password_confirmation]
    # the next line clears the temporary token and updates the password
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Пароль успешно изменён.')
    else
      render :action => "edit"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :check_app_auth, only: [:new, :create, :activate]
  skip_before_filter :require_login, :only => [:index, :new, :create, :activate]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def activate
    if (@user = User.load_from_activation_token(params[:id]))
      @user.activate!
      redirect_to(login_path, :notice => 'Адрес электронной почты подтверждён.')
    else
      not_authenticated
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, 
        :activation_state, :activation_token, :activation_token_expires_at)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :check_app_auth
  before_action :require_login, only: :destroy
  
  def index
  end 

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(root_path, notice: 'Вход выполнен')
    else
      flash[:danger] = "Неверный #{User.human_attribute_name(:email).mb_chars.downcase} или
#{User.human_attribute_name(:password).mb_chars.downcase}"
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Сеанс работы в системе завершен')
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  def error_messages_for(object)
    render 'error_messages_for', object: object
  end

  def error_messages_for_attr(object, attr)
    if object.present? 
      render 'error_messages_for_attr', object: object, attr: attr
    else
      ''
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/side_bar_helper.rb
module SideBarHelper
  def side_bar_items(ru)
    result = []
    result << {
      :name => 'Сслыка без детей',
      :icon => 'list',
      :controller => :welcome, 
      :action => :index
    }
    result << {
      :name => 'Администрирование',
      :icon => 'users',
      :children => [
      {:name => 'Пользователи',
       :controller => :users, :action => :index,
       :icon => 'file-text-o',
       :class => 'long'},
      {:name => 'Добавление',
       :controller => :users, :action => :new,
       :icon => 'user-plus'}
    ]} 
    result << {
      :name => 'Заголовок ссылок',
      :icon => 'search-plus',
      :children => [
      {:name => 'Ссылка ребёнок',
       :controller => :welcome, :action => :index,
       :icon => 'binoculars'},
      {:name => 'Ссылка ребёнок',
       :controller => :welcome, :action => :index,
       :icon => 'search',
       :class => 'long'}
    ]} 
    result
  end
  
  def is_open?(ctr, act)
    case ctr.to_s
    when 'users'
      ctr.to_s == controller_name.to_s  
    else
      false
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/_breadcrumb.html.haml
-content_for :breadcrumb do
  %ul.breadcrumb.hidden-print
    = block

app/views/application/_error_messages_for.html.haml
-if object.errors.present?
  .alert.alert-danger
    %h4 При сохранении произошли ошибки
    %ul
      -object.errors.full_messages.each do |msg|
        %li=msg

app/views/application/_error_messages_for_attr.html.haml
-if object.errors[attr].present?
  .text-danger
    %ul.list-unstyled
      -object.errors.delete(attr).each do |msg|
        %li=msg

app/views/application/_flash_messages.html.haml
-flash.each do |key,val|
  .growl-msg{data: {type: key.to_s=='notice' ? 'success' : key}}=val

app/views/application/_navbar_top.html.haml
%nav.navbar.navbar-inverse.hidden-print#top-bar
  .container-fluid
    .navbar-header
      .navbar-brand
        = link_to root_path do
          = image_tag 'logo.png', alt: t('app.company.short_name')
          = t('app.name')
      %button.navbar-toggle.collapsed{type: 'button', data: {toggle: 'collapse', target: '#bs-example-navbar-collapse-1'}}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    %ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse#bs-example-navbar-collapse-1
      %li
        = link_to login_path do
          = @current_user.blank? ? 'войти' : @current_user.email
      %li
        - if @current_user.blank?
          = link_to login_path do
            = fa_icon 'sign-in'
        - else
          = link_to logout_path do
            = fa_icon 'sign-out'

app/views/application/_sidebar.html.haml
%aside.hidden-print#sidebar-wrapper
  %ul.sidebar-nav
    - side_bar_items(@current_role_user).each do |item|
      %li
        - if item.has_key?(:children)
          = link_to('#', class: 'with-subitems') do
            = fa_icon(item[:icon], class: 'menu-icon')
            = item[:name]
            %span.pull-right.carret
              = fa_icon('angle-down', class: 'menu-icon')              
          %ul.subitems{class: (item[:children].any?{ |subitem| is_open?(subitem[:controller], subitem[:action]) } ? :subopen : :subclose)}
            - item[:children].each do |subitem|
              %li.subitem
                - if subitem.has_key?(:params)
                  = link_to(url_for({controller: subitem[:controller], action: subitem[:action]}.merge(subitem[:params])), class: subitem[:class]) do        
                    = fa_icon(subitem[:icon], class: 'menu-icon')
                    = subitem[:name]
                - else
                  = link_to(url_for(controller: subitem[:controller], action: subitem[:action]), class: subitem[:class]) do        
                    = fa_icon(subitem[:icon], class: 'menu-icon')
                    = subitem[:name]
        - else
          = link_to(url_for(controller: item[:controller], action: item[:action]), class: item[:class]) do
            = fa_icon(item[:icon], class: 'menu-icon')
            = item[:name]
    %li.footer
      %div
        © В.Ю. Радыгин

app/views/application/access_denied.html.haml
%h1
  Доступ запрещён!

.alert.alert-danger
  Пользователю 
  = @current_user.nil? ? 'не авторизован' : @current_user.email
  к действию
  = action_name
  контроллера
  = controller_name
  доступ запрещён!  

= link_to 'Назад', login_path

app/views/application/error.html.haml
.alert.alert-danger=@error

app/views/layouts/application.html.haml
!!!
%html{lang: 'ru'}
  %head
    %title=t('app.name')
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: "width=device-width, initial-scale=1.0"}
    %meta{'http-equiv'=>"X-UA-Compatible", 'content'=>"IE=edge"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    =favicon_link_tag 'favicon.ico'
    =favicon_link_tag 'favicon-32x32.png', sizes: '32x32'
    =favicon_link_tag 'apple-icon.png', rel: 'apple-touch-icon'

  %body
    =render 'application/navbar_top'
    #wrapper
      =render 'application/sidebar'
      #page-content-wrapper
        .container-fluid
          %span.hidden-print#sidebar-toggle
            = link_to "#wrapper", class: 'sidebar-toggle' do
              = fa_icon('ellipsis-v')
          =render 'flash_messages'
          -if content_for? :breadcrumb
            =yield :breadcrumb
          -if content_for? :error_messages
            =yield :error_messages
          = yield
  .modal.fade#loader{tabindex: -1, role: 'dialog', 'aria-labelledby' => 'myModalLabel'}
    .modal-dialog.mymodal{role: 'document'}
      =image_tag 'gears.gif'

app/views/password_resets/edit.html.haml
%h1
  Установите новый пароль
= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f|
  =error_messages_for @user
  .row
    .col-md-5
      .form-group
        = f.label :email
        = @user.email
  .row
    .col-md-5
      .form-group
        = f.label :password
        = f.password_field :password, class: 'form-control'
  .row
    .col-md-5 
      .form-group
        = f.label :password
        = f.password_field :password_confirmation, class: 'form-control'
  .form-actions
    = f.submit "Сменить пароль", class: 'btn btn-primary'

app/views/password_resets/new.html.haml
%h1
  Забыли пароль?
= form_tag password_resets_path, :method => :post do
  .row
    .col-md-5
      = label_tag("email", "Адрес электронной почты:") 
      = text_field_tag :email, '', class: 'form-control'
  .form-actions
    = submit_tag "Сменить", class: 'btn btn-primary'

app/views/users/_form.html.haml
= form_for @user do |f|
  = error_messages_for @user
  .row
    .col-md-4
      .form-group
        = f.label :email
        = f.text_field :email, class: 'form-control'
        = f.error_messages_for(:email)
    - if @user.new_record?
      .col-md-4
        .form-group
          = f.label :password
          = f.password_field :password, class: 'form-control'
          = f.error_messages_for(:password)
      .col-md-4
        .form-group
          = f.label :password_confirmation
          = f.password_field :password_confirmation, class: 'form-control'
          = f.error_messages_for(:password_confirmation)
  .form-actions
    = f.submit nil, class: 'btn btn-primary'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
.page-header
  %h1 Новый пользователь

= render 'form'

app/views/users/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/welcome/_form.html.haml
= form_tag try_login_path, :method => :post do
  .row
    .col-md-6
      .form-group
        .input-group.input-group-md
          %span.input-group-addon.px50
            %i.fa.fa-user
          = text_field_tag :email, '', class: 'form-control', placeholder: User.human_attribute_name(:email)
  .row
    .col-md-6 
      .form-group
        .input-group.input-group-md
          %span.input-group-addon.px50
            %i.fa.fa-key
          = password_field_tag :password, '', class: 'form-control', placeholder: User.human_attribute_name(:password)
  .row
    .col-md-6 
      .checkbox
        %label
          = check_box_tag :remember_me, false, true
          Запомнить меня 
  .row
    .form-actions
      .col-md-2
        = submit_tag "Войти", class: 'btn btn-primary'
      .col-md-2      
        = link_to 'Забыли пароль?', new_password_reset_path, class: 'btn'
      .col-md-2
        = link_to 'Регистрация', new_user_path, class: 'btn'

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml

app/views/welcome/new.html.haml
.page-header
  %h1
    Вход в 
    = t('app.name')

= render 'form'